imports:
    - { resource: parameters.yml }
    - { resource: version.php }
    - { resource: security.yml }
    - { resource: dashboard.yml }

jms_di_extra:
    locations:
        bundles: [AppBundle]
    doctrine_integration: false

zenstruck_media:
    default_layout: ::base.html.twig
    media_form_type: true
    slugify_filename_filter: true
    filesystems:
        Files:
            root_dir: %kernel.root_dir%/../web/files/files
            web_prefix: /files/files
        Images:
            root_dir: %kernel.root_dir%/../web/files/images
            web_prefix: /files/images
            allowed_extensions: jpg, gif, png

zenstruck_form:
    form_types:
        tunnel_entity: true
        ajax_entity: true
        ajax_entity_controller: true
        help: true
        group: true

zenstruck_cache:
    sitemap_provider:     true

framework:
    esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %app.build%
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'ZenstruckFormBundle:Twitter:form_bootstrap_layout.html.twig'
            - 'ZenstruckMediaBundle:Twitter:form_media_type.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%uglifyjs_path%"
        uglifycss:
            bin: "%uglifycss_path%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
