Sandbox\AppBundle\Entity\Author:
    user{1..50}:
        name: <firstName()>

Sandbox\AppBundle\Entity\Tag:
    tag{1..200}:
        name: <word()>

Sandbox\AppBundle\Entity\Article:
    post{1..30}:
        title: <text(100)>
        body: <text(500)>
        cost: <randomFloat(1, 0, 100.00)>
        author: @user*
        editor: @user*
        tags: <numberBetween(0, 3)>x @tag*
        date: <dateTimeBetween('-5 years')>

Sandbox\AppBundle\Entity\Link:
    link{1..30}:
        url: <url()>
        article: @post*