zenstruck_dashboard:
    resource: "@ZenstruckDashboardBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

zenstruck_form:
    resource: "@ZenstruckFormBundle/Resources/config/ajax_entity_routing.xml"

zenstruck_media:
    resource: "@ZenstruckMediaBundle/Controller/MediaController.php"
    type:     annotation
    prefix:   /media

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
